### ISSUE TITLE
Support custom renderers

### ISSUE THREAD

**Issue by Kureev** [airbnb/react-sketchapp#119]
Hello 👋 

**Motivation:** In my current company we want to try `react-sketchapp`. Although, it seems that in it's current shape, react-sketchapp supports only a limited subset of React Native components. I'm not sure if its a problem for us, but I think that having an opportunity to create custom renderers will help us to overcome potential issues in the future.

**Issue:** In its current state, `react-sketchapp` can't be extended with custom renderers.

**Proposed solution:** Create a mechanism that injects custom renderers. As I see from the code, the only place you use renderers is in `flexToSketchJSON`. This function is used in file `render.js`, function `render`. So my proposal is to supply a third argument to the `render` function: 
```js
(element: React$Element<any>, container: SketchLayer, renderers: Renderers): ?SketchLayer
```
Thus, `flexToSketchJSON` won't import `./renderers` from itself, but use a given parameter instead. 

Later, in user project, in the file manifest is pointing to, supply a third argument to the `render` like this:

```js
import customRenderers from './customRenderers';
//...
render(<Document colors={colorList} />, context.document.currentPage(), customRenderers);
```

Of course, in order not to break things, third argument should be optional. This is how I see `render.js`:

```js
import renderers from './renderers';
//...
export const render = (element: React$Element<any>, container: SketchLayer, customRenderers: Renderers): ?SketchLayer => {
  if (appVersionSupported()) {
    try {
      const tree = buildTree(element);
      return renderToSketch(tree, container, { ...rendereres, ...customRenderers });
    } catch (err) {
      const tree = buildTree(<RedBox error={err} />);
      return renderToSketch(tree, container, renderers);
    }
  }
  return null;
};
```

Please, let me know if you like the proposed approach so I can compose a PR

**Comment by jongold** [comment]
Thanks for the thoughtful issue!

I'm keen to be proven wrong, but our current thought process:
- a large majority of Airbnb's app is built with a handful of components
- the rest can pretty much all be implemented using `<View>` and `<Text>` etc
- there might be some exceptions!

I highly recommend watching [React as a Platform](https://www.youtube.com/watch?v=hNwQPJy-XZY) for more context on this :)

I built out [a basic working example](https://snack.expo.io/r1XgaohG-) — in this manner I can see someone writing a library of `react-primitives-components` or something, and then…

```js
/* components/ToggleRow.js */
import { Switch } from 'react-primitives-components'
import { View, Text } from 'react-primitives'

export default props =>
  <View>
    <Text>{ props.title }</Text>
    <Switch value={props.switchValue} onValueChange={props.onValueChange}</Switch>
  </View>
```

```js
/* react-sketchapp-entry-point.js */
import { render } from 'react-sketchapp';
import { ToggleRow } from './components/ToggleRow'

export default context =>
  render(
    <ToggleRow title='should designers learn to code?' switchValue={true} />,
    context.document.currentPage()
  );
```

Cross platform components, no need to inject renderers. I'd definitely rather stick to the Primitives API as much as possible - any exceptions so far are Sketch-specific things (Artboard, TextStyles etc)

I can't think of any components right now that can't be implemented with Text, View & Image (that's why they're called _primitives_), but let me know if my suggestion doesn't work for your use case :)

**Comment by Kureev** [comment]
Thanks for this great and detailed answer, @jongold! I also appreciate lots of additional resources you linked to it 👍 

Indeed, this approach works in most cases, but how can it cover missing components? I can't think of many examples, but this is first that comes to my mind: in our application we use FlatList. It'll be very handy if we can import our existing components, wrap them into `Artboard` from `react-sketchapp` and render them to sketch. Apparently, it isn't possible if we use components that are more complex than composition of View or Text and that's why I wanted to find a way to supply a custom renderer for a FlatList (for instance). I believe this is also relevant for all non-standard React Native components, built by community.
