### ISSUE TITLE
Redux store

### ISSUE THREAD

**Issue by dominikchrastek** [airbnb/react-sketchapp#122]
Hello, is it possible to inject redux store to the component, that is rendered to sketch?

**Comment by jongold** [comment]
I'm not sure, I haven't tried it yet! I don't have time to look into it right now, but you should give it a go and let us know what happens — we can add bugs to the issues list to work on (or we'd love contributions) :)

Components won't update (because they're not clickable), but we could get it working at least so that you can reuse your same code across web / native / sketch :)

That said, remember that in idiomatic redux your components should be 'dumb' and all the `connect` stuff should be happening in a container component :)

**Comment by jongold** [comment]
Ignore ^^^ - I couldn't stop thinking about it so I had a look. It seems to work :)

https://github.com/airbnb/react-sketchapp/pull/124
