### ISSUE TITLE
web.js

### ISSUE THREAD

**Issue by LincMitch** [airbnb/react-sketchapp#175]
Firstly - ReactSketchApp is Awesome THX THX THX! 

I have a question (not an issue) so is this the right place to ask?

Q. 
A couple of examples use 'npm run web' but can all the examples do this? If so, is it hard to setup? I can kinda see what's happening in the code but have little react exposure so wanted to ask 1st before I try.

For me to sell this workflow to colleagues, I'll need to demonstrate how they take anything I do in ReactSketchApp as input into generating final front end code. 

They don't use React currently, they use jQuery. Having our Designers code in React, means we not only gain respect from the developers, we can now lead the FED technology and encourage them to keep up.

Link

**Comment by LincMitch** [comment]
I now understand what Primitives are, and that the examples use them. That being:
- profile-cards-primitives
- styled-components

As my code uses styled-components I figured I'd get that example working 1st. 
Unfortunately, the demo only renders to Sketchapp and I can't work out how to render to web. Was expecting to see a web.js file.

Any help appreciated.

**Comment by ianhook** [comment]
So there are 2 big differences between profile-cards-primitives and styled-components:
1) `npm i nwb` - styled-components does not have this package installed, so it doesn't have anyway to setup a server locally to display your react.
2) `web.js` - this is the entry point for a web React app. This has to be different from the Sketch version because web and Sketch expect different things. The basic shell looks like

```
import React from 'react';
import Blah from './your/cool/component/Blah';

export default () => (
  <div>
    <Blah />
  </div>
);
```

Once you have both of these things, you'll to [copy this line over](https://github.com/airbnb/react-sketchapp/blob/master/examples/profile-cards-primitives/package.json#L12) to the `package.json` file in your project, which will allow you to run `npm run web`.

That said you may want to learn more about React in general. A good place to start might be the documentation for NWB, which you're using to run you web app, https://github.com/insin/nwb.

**Comment by LincMitch** [comment]
Thx heaps for the leg up. Will try that

**Comment by LincMitch** [comment]
Getting closer. I now have 'nwb' in node_modules folder.
But I get the error: "react: command not found". 

Also, do I need this line?:
import { render } from 'react-dom';

Will check out the documentation for NWB.

**Comment by jongold** [comment]
Did you get this solved in the end?

nwb certainly isn't a must-have - it's just the quickest way I could think of to get a React app to compile in the browser without lots of config - you could equally use create-react-app, or your own webpack config.

What you _do_ need is React Primitives (or some other abstraction) to delegate to react-sketchapp / react-dom as appropriate :)

**Comment by LincMitch** [comment]
Yes - worked it out (didn't end up using nwb).
