### ISSUE TITLE
Removing project bottlenecks

### ISSUE THREAD

**Issue by jongold** [airbnb/react-sketchapp#209]
Hey y'all! Super impressed with all of the progress people have been making on this project recently.

Can we take a sec to discuss high-level project maintenance? I have some questions / discussion points:

### I have this perception that I'm being a bottleneck
- _sorry_
- is this a fair assessment?
- My time for this project is super limited right now so I want to figure out ways for that not to be the case.

### Do we have enough maintainers?
- I've been pretty liberal with adding people who have made big contributions / have strong opinions recently.
- Should we add more?

### Do maintainers feel empowered to maintain?
- are y'all confident making calls on merging PRs etc?
- We have 8 open PRs right now — why?

### Can anyone else publish the npm package?
- I have a feeling that I'm the only person who has made releases historically
- I have a feeling that this is the main place I'm holding up the project progress
- do other projects distribute this responsibility? how?
- I've never added people as collaborators on npm but I'm totally happy to do that

cc @ianhook @larsonjj @ljharb @mathieudutour etc, without any expectation of me putting extra work on any of your plates :P

**Comment by ljharb** [comment]
@jongold ah, that's an oversight; please run `npm owner add airbnb` at the least :-). After that, if you want to write up a markdown document for the repo that documents your publishing process, if any, that will enable more people to handle it for you.

Separately, having open PRs, even for a long time, isn't necessarily a sign of staleness or people being blocked - sometimes PRs need time to bake, sometimes the author isn't responsive, and sometimes the maintainers aren't sure that the PR should land at all, even if it's otherwise mergeable.
