### ISSUE TITLE
Would be great if it worked in the opposite direction

### ISSUE THREAD

**Issue by talkaboutdesign** [airbnb/react-sketchapp#32]
I am a product designer. This tool looks great .

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------

Would love ability to generate React code based on Sketch Artboard. Essentially ability to go back and fourth.

**Comment by jongold** [comment]
Me too, me too.

I think for the scope of this project it's unlikely that we'll go back-and-forth anytime soon (you can't modify the DOM and update a React component), but it might be feasible to use react-sketchapp in conjunction with another project and wrap them up together :)

Hope you don't mind if I close this ticket, but I appreciate the feedback 🙏

**Comment by talarari** [comment]
Hey, from reading the FAQ,  I understand going only react->sketch is intentional.
two questions:
1. does this mean designers at airbnb design in code? or they just load the design system to sketch and create a normal sketch file as output for a new feature/screen?
2. would be awesome if you could share your opinion on the feasibility of sketch-> react direction, based on your experience with sketch's api (json format,plugins etc).

thanks!

**Comment by jongold** [comment]
@talarari 

1. no - to edit the design system you still have to code, but this is the same as before — to make a real production component you'd _still have to write code_, so essentially nothing changes. we're working on a component editor for updating the design system though 🤔 🤐 

2. it's out of scope of this project, but good luck if you want to try it! it's relatively simple to make a proof-of-concept exporter with absolute positions etc, but it gets really complicated once you start thinking about dataflow & flexbox etc
