### ISSUE TITLE
Node implementation can't handle some SVG paths

### ISSUE THREAD

**Issue by hadihallak** [airbnb/react-sketchapp#467]
Try to render this SVG to JSON using the node implementation:
```jsx
<Svg width="10" height="10" viewBox="0 0 10 10">
   <Svg.Path d="M11.467 3.727c.289.189.37.576.181.865l-4.25 6.5a.625.625 0 01-.943.12l-2.75-2.5a.625.625 0 01.84-.925l2.208 2.007 3.849-5.886a.625.625 0 01.865-.181z"></Svg.Path>
</Svg>
```

**Expected behavior:**
Output correct sketch SVG structure

**Observed behavior:**
creates broken sketch SVG structure which can't run in Sketch and as you can see in the sandbox it will create a frame with infinity properties:

<img width="260" alt="Screen Shot 2020-01-16 at 8 58 13 AM" src="https://user-images.githubusercontent.com/13556017/72494766-57c6de00-383e-11ea-98c7-c679bb5e02dc.png">

was able to track it down to the `lona/svg-model` package which if you pass it this SVG then it will output the SVG path with no commands but that's about as far as I was able to get since the `lona/svg-model` isn't public

another note is that this same SVG if you copy and paste into sketch it will not render very well in comparison to Figma or the browser 
 

**How to reproduce:**
see sandbox below

**Sketch version:**
61.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
https://codesandbox.io/s/infallible-lehmann-vplez

**Comment by mathieudutour** [comment]
Ah indeed, I'll get `lona/svg-model` open source and we can move the issue there

**Comment by mathieudutour** [comment]
-> https://github.com/Lona/svg-model

**Comment by mathieudutour** [comment]
So I tried to debug and it's because the path is a bit "malformed". Browsers are managing to parse it but it's ambiguous.
`a.625.625 0 01.84-.925` is supposed to be parsed as `a 0.625 0.625 0 0 1 0.84 -0.925`. Notice how `01.` become `0 1 0.`. The [library](https://github.com/fontello/svgpath) we are using to parse the path assumes that a parameter is missing instead.
I'll open an issue there to track it.

In the meantime, you can use a "properly" formatted path: `M 11.467 3.727 c 0.289 0.189 0.37 0.576 0.181 0.865 l -4.25 6.5 a 0.625 0.625 0 0 1 -0.943 0.12 l -2.75 -2.5 a 0.625 0.625 0 0 1 0.84 -0.925 l 2.208 2.007 3.849 -5.886 a 0.625 0.625 0 0 1 0.865 -0.181z`

**Comment by hadihallak** [comment]
@mathieudutour Thanks a lot for looking into this 🙌 

A solution seems to have already been published to `fontello/svgpath`
Will test it tomorrow and will let you know how it goes

**Comment by mathieudutour** [comment]
should be fixed now (I added a test on the svg-model repo and it works fine)
