### ISSUE TITLE
Move from css-layout to yoga

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/react-sketchapp#52]
Yoga now has an [emscripten target](https://facebook.github.io/yoga/docs/api/javascript/) and it would be good for us to move over to it instead of using css-layout. Yoga is now what React Native is using, and this will give us the highest level of consistency with those platforms.

**Comment by jongold** [comment]
Any idea of an estimate? We might need a label bigger than `1 day`

**Comment by lelandrichardson** [comment]
@jongold 1 day seems reasonable. It shouldn't be that hard. the surface area for the css-layout stuff right now is pretty small and it should work somewhat similarly

**Comment by mathieudutour** [comment]
I started looking into yoga (because I didn't play with it yet) here: https://github.com/airbnb/react-sketchapp/commit/a9a21fa9300ffa7bf3ddcd2855f7a25ba30d72fa

Unfortunately there is no documentation for the emscripten target and the document for css-layout seems to have disappeared.

One thing tho: I'm not sure there is a way to define `margin-top` only for example: https://github.com/facebook/yoga/blob/master/javascript/sources/Node.hh#L69
