### ISSUE TITLE
Request for "How to" for developing components for mobile applications

### ISSUE THREAD

**Issue by hhimanshu** [airbnb/react-sketchapp#54]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am..._ an engineer (backend mostly) and learned how to use Sketch

| -------------------------------------------------------------------------------------------------
| Requesting a new feature
| -------------------------------------------------------------------------------------------------
I looked at the source code and got confused with few things
- How do I use Sketch's Templates for iOS, Android, Responsive Web Design
- How to utilize Material Design Components (which we generally get from Sketch App Resources)
- The `main-command.js` has components like `View`, `Artboard` which are coming from `react-sketchapp`, which I believe I do not have to take it to my `react` app. The guidance needed it how to take these designs to our `react` application.

Thank you very much for the project, this is very promising for people who love to code to design

**Sketch version:**
43.2

**Comment by jongold** [comment]
Hey Harit! Sorry for missing this one…

There’s no direct compatibility with anything from the `File -> New From Template` menu unfortunately.

To be able to render React components into Sketch we need React components!

That said, there’s a path going forward…

Theoretically, you should be able to use React component libraries (especially those designed for React Native, or ideally built with [React Primitives](https://github.com/lelandrichardson/react-primitives) — see [this talk](https://www.youtube.com/watch?v=hNwQPJy-XZY). At Airbnb we import our real components and use them for prototyping —
```js
import { Foo, Bar, Baz } from ‘our-component-library’
import { render, View } from ‘react-sketchapp’

export default (context) =>
  render(<View><Foo /><Bar /></View>, context.document.currentPage())
```

You could do the same for Material UI components _but I haven't found one that works yet_. I'd love to have a list of references for great component libraries built with `react-primitives`, but that's also outside the scope of this project.

As for _why_ you'd want to do things this way rather than just using Sketch templates - some thoughts:
- Use the components as they're designed and implemented rather than creating a secondary 'design reference'
- Handle reflowing text & elements etc
- Using real data from an API rather than from Craft
![image](https://user-images.githubusercontent.com/591643/27049960-c7e4ff1a-4f65-11e7-960a-7c87492e2b88.png)

Also (and I don't know if / when we'll release this, but you could make your own!) — [Sketch plugins that use those real components](https://twitter.com/jongold/status/866854672421634049). This hints at the vision for `react-sketchapp` :)
